services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: github-repo-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - GITHUB_TOKEN=${GITHUB_TOKEN:-your_github_personal_access_token_here}
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/repos/stats"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    networks:
      - github-repo-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: github-repo-frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - github-repo-network

networks:
  github-repo-network:
    driver: bridge

volumes:
  # Optional: Add volumes for persistent data if needed in the future
  backend-data: